resources/urls.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2012.03.12
#
# For help with all the now undocumented updates, see:
#    http://code.djangoproject.com/wiki/NewFormsAdminBranch
#
# For help with the images and css, see:
#    http://www.djangoproject.com/documentation/static_files/
#
# See also?
#    http://code.djangoproject.com/wiki/IrcFAQ#MediaURL
#    http://www.djangoproject.com/documentation/templates_python/#subclassing-context-requestcontext
#    http://www.djangoproject.com/documentation/settings/#media-root
#    http://www.djangoproject.com/documentation/settings/#media-url
#
# 2008.11.30 KJC - DEPLOY! Added "django/" to all patterns (See p. 279)
# 2008.12.01 KJC - Oops. Changed "^django/" to "^". See updated info at:
#                  http://docs.djangoproject.com/en/dev/howto/deployment/modpython/
# 2008.12.01 KJC - Split into multiple urls.py files
# 2009.09.18 KJC - Changed ^admin/ to upcoming Django 1.3 format
# 2012.02.22 KJC - Refactored / merged from /psite/ into this "instance"
# 2012.03.11 KJC - Adding in Research at Gallaudet (rag)
# 2012.03.12 KJC - Changing it to Research at Gallaudet University (ragu)
# 2012.05.02 KJC - Adding in Preliminary Screening Survey (screening)
# 2013.11.10 KJC - Adding an International Visitors form...

from django.conf.urls.defaults import patterns, include, url
from django.contrib            import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #   url(r'^$',          'resources.views.home', name='home'),
    #   url(r'^resources/', include('resources.foo.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/',     include(admin.site.urls)),

    url(r'^books/',     include('resources.books.urls')),
    url(r'^mhd/',       include('resources.mhd.urls')),
    url(r'^ragu/',      include('resources.ragu.urls')),
    url(r'^screening/', include('resources.screening.urls')),
    url(r'visitors/',   include('resources.visitors.urls')),

    # Probably now a better way to handle the following two lines...
    #url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/kjcole/Django/images'}),
    #url(r'^css/(?P<path>.*)$',    'django.views.static.serve', {'document_root': '/home/kjcole/Django/css'}),
)

resources/visitors/urls.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2014.03.06
#
# 2013.07.16 KJC - Switching to class-based generic views from function-based
# 2014.03.06 KJC - index is now oldindex and testicle is now index.
#

from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from resources.visitors.views  import *

urlpatterns = patterns("",
    (r"^$",                          index),
#   (r"^test/$",                     testicle),
    (r"^api/feed/$",                 feed),
    (r"^bios/(\d{1,6})/$",           bios),
    (r"^thanks/(\d{1,6})/$",         thanks),
)

resources/visitors/models.py
# Models for the International Visitors Request Form
# Last modified by Kevin Cole <kjcole@gallaudet.edu> 2013.12.01
#

from django.db import models

SHIFT   = ((1, "Morning"),
           (2, "Midday" ),
           (3, "Evening"))

YEA_NAY = ((True,  "Yes"),
           (False, "No" ))

class Language (models.Model):
    iso3 = models.CharField("ISO 3-letter",max_length=3,editable=False)
    iso2 = models.CharField("ISO 2-letter",max_length=2,editable=False,null=True)
    name = models.CharField(max_length=80, editable=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "languages"

class Country (models.Model):
    id   = models.IntegerField(primary_key=True, editable=False)
    name = models.CharField(max_length=80, editable=False)
    iso3 = models.CharField("ISO 3-letter",max_length=3,editable=False)
    iso2 = models.CharField("ISO 2-letter",max_length=2,editable=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "countries"

class Inquiry (models.Model):
    changed      = models.DateTimeField("last changed", auto_now=True, editable=False)
    arr_date     = models.DateField("arrival date")
    arr_time     = models.PositiveSmallIntegerField("arrival time",null=True,choices=SHIFT)
    dep_date     = models.DateField("departure date")
    dep_time     = models.PositiveSmallIntegerField("departure time",null=True,choices=SHIFT)
    requester    = models.CharField(max_length=80)
    organization = models.CharField(max_length=80)
    email        = models.CharField(max_length=80)
    phone        = models.CharField(max_length=80)
    visitors     = models.PositiveSmallIntegerField()
    speakers     = models.PositiveSmallIntegerField()
    signers      = models.PositiveSmallIntegerField()
    purpose      = models.TextField()
    letters      = models.BooleanField("letters?", choices=YEA_NAY)
    countries    = models.ManyToManyField(Country)

    def _interpreter_needed(self):
        """Build a computed pseudo-field named "interpreter"."""
        if self.signers < self.visitors: return True
        else:                            return False
    interpreter = property(_interpreter_needed)

    def __unicode__(self):
        return "%s - %s" % (self.arr_date, self.organization,)

    class Meta:
        ordering = ["arr_date", "organization"]
        get_latest_by = "changed"
        verbose_name_plural = "inquiries"

class Visitor (models.Model):
    changed     = models.DateTimeField("last changed",auto_now=True,editable=False)
    inquiry     = models.ForeignKey(Inquiry)
    surname     = models.CharField(max_length=80)
    givenname   = models.CharField("given name",max_length=80)
    middlename  = models.CharField(max_length=80, null=True)
    occupation  = models.CharField(max_length=80)
    gender      = models.CharField(max_length=1)   # Should this be PosSmallInt?
    dob         = models.DateField("date of birth")
    citizenship = models.ForeignKey(Country, related_name="citizens")
    native      = models.ForeignKey(Country, related_name="natives")
    residence   = models.ForeignKey(Country, related_name="residents")
    passport    = models.CharField(max_length=80, null=True)

    def __unicode__(self):
        return "%s, %s" % (self.surname, self.givenname,)

    class Meta:
        ordering = ["citizenship", "surname", "givenname"]
        get_latest_by = "changed"
        verbose_name_plural = "visitors"

resources/visitors/views.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2014.03.06
#
# This contains the functions to which URL's are mapped by 
# urls.py.
#
# 2014.03.06 KJC - index is now oldindex and testicle is now index.
#

import random              # DEBUG

import json                # JSON for jQuery AJAX autocomplete
from   datetime            import timedelta, datetime, date

from django.http           import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts      import render_to_response, get_object_or_404
from django.db.models      import Q
from django.template       import RequestContext
from django.forms.models   import inlineformset_factory
from django.contrib.auth   import authenticate, login
from django.core.paginator import *

from django.core.mail      import send_mail, EmailMultiAlternatives
from django.template       import Context, loader

from resources.visitors.models import Language, Country, Inquiry, Visitor
from resources.visitors.forms  import InquiryForm, VisitorForm

#from resources.screening.forms import AgencySourcesForm,        \
#                                      AgencyContactForm,        \
#                                      AgencyParticipationForm,  \
#                                      PrivateCountsForm,        \
#                                      PrivateSourcesForm,       \
#                                      PrivateContactForm,       \
#                                      PrivateParticipationForm, \
#                                      PublicCountsForm

months    = ("January","February","March","April","May","June","July",
             "August","September","October","November","December",)
instant   = datetime.now()
today     = date.today()
#yesterday = today - timedelta(1)
#year_ago  = today - timedelta(365)
#thisyear  = today.year
#lastyear  = thisyear - 1
#fiscal    = today.year + (today.month // 10)    # Now in fiscal year "fiscal"
#years     = range(thisyear-50,thisyear+10)
#lastfy    = (date(lastyear,10,1), date(lastyear,9,30)) # Last fiscal year range

##############################################################################
#
# The following function was copied on 2012.08.10 from
#
#   http://www.redrobotstudios.com/blog/2009/02/18/securing-django-with-ssl/
#
# Securing individual pages...  To use, add "@secure_required"
# immediately above any function that requires an https connection.
#
# Note: The original version of this function, on the web site above,
# checks for HTTPS_SUPPORT = True in settings.py.  However, could not
# find such a setting anywhere in the Debian package nor in the
# official Django documentation. So this check has been removed here.
#
##############################################################################

def secure_required(view_func):
    """Decorator makes sure URL is accessed over https."""
    def _wrapped_view_func(request, *args, **kwargs):
        if not request.is_secure():
            request_url = request.build_absolute_uri(request.get_full_path())
            secure_url  = request_url.replace('http://', 'https://')
            return HttpResponseRedirect(secure_url)
        return view_func(request, *args, **kwargs)
    return _wrapped_view_func

# End copied code

##############################################################################

def feed(request):
    """Auto-complete country names"""
    if request.is_ajax():
        term = request.GET.get("term","")
        countries = Country.objects.filter(name__istartswith=term)
        if countries.count() == 0:
            countries = Country.objects.filter(name__icontains=term)
        results = []
        for country in countries:
            country_json = {}
            country_json["label"] = country.name
            country_json["value"] = country.name
            country_json["id"]    = country.id
            results.append(country_json)
        data = json.dumps(results)         # Convert to JSON string
    else:                                  # No results returned!
        data = "fail"                      # ERROR!
    mimetype = "application/json"
    return HttpResponse(data, mimetype)    # Send JSON back to the web page

def oldindex(request):
    countries = Country.objects.all()
    if request.method == "POST":
        inquiry_form = InquiryForm(request.POST)
        if inquiry_form.is_valid():
            inquiry = inquiry_form.save()
#           return HttpResponseRedirect("/resources/visitors/bios/%s" % (inquiry.id,))
            origins = int(request.POST["origins"])
            for origin in range(1,origins+1):
                try:
                    country_id = int(request.POST["country.%s" % origin])
                    if country_id:
                        country = Country.objects.get(pk=country_id)
                        inquiry.countries.add(country)
                except ValueError:
                    pass
            return HttpResponseRedirect("/resources/visitors/thanks/%s/" % (inquiry.id,))
        else:
           return render_to_response("visitors/index.html", locals(),
                              context_instance=RequestContext(request))
    else:
        inquiry_form = InquiryForm()
    return render_to_response("visitors/index.html", locals(),
                              context_instance=RequestContext(request))

##############################################################################

def thanks(request,inquiry_id):
    inquiry   = get_object_or_404(Inquiry, pk=int(inquiry_id))
    countries = inquiry.countries.all().order_by("id")
    visitors  = Visitor.objects.filter(inquiry=inquiry)

    today     = date.today()
    subject   = "Re: Visit Inquiry - "
    subject  += countries[0].name.upper() + " ("
    subject  += inquiry.arr_date.strftime("%B %d, %Y") + " to "
    subject  += inquiry.dep_date.strftime("%B %d, %Y")  + ")"
    sender    = "International Visitor Form <gri.gateway@gallaudet.edu>"
    to        = ["%s <%s>" % (inquiry.requester,inquiry.email,),]
    bcc       = ["intl.visit@gallaudet.edu",]
    extras    = {"Reply-To": "intl.visit@gallaudet.edu",}
#                "MIME-Version": "1.0",
#                "Content-type": "text/html; charset=iso-8859-1",}
    body      = "Your request has been received."
    filler    = Context(locals())
    html      = loader.get_template("visitors/deliver.html")
    msg = EmailMultiAlternatives(subject, body, sender, to, bcc,
                                 headers=extras)
    msg.attach_alternative(html.render(filler), "text/html")
##  msg.attach("save_as.png", png_raw_data, "image/png")
#   msg.attach_file("/var/www/html/images/logos/Gallaudet-750.png",
#                   "image/png")
    html = loader.get_template("visitors/receipt.html")
    msg.attach("receipt.html", html.render(filler), "text/html")
    SHIFT     = {1:"Morning", 2:"Midday", 3:"Evening"}
    NEEDED    = {True:"Needed", False:""}
    tsv       = "Countries\tArrival\tDeparture\tRequester\tOrganization\t"
    tsv      += "Email\tPhone\tVisitors\tSpeakers\tSigners\tLetters\n"
    tsv      += "%s\t"         % (inquiry.countries.all()[0],)
    tsv      += "%s %s\t"      % (inquiry.arr_date, SHIFT[inquiry.arr_time],)
    tsv      += "%s %s\t"      % (inquiry.dep_date, SHIFT[inquiry.dep_time],)
    tsv      += "%s\t%s\t"     % (inquiry.requester, inquiry.organization,)
    tsv      += "%s\t%s\t"     % (inquiry.email, inquiry.phone,)
    tsv      += "%s\t%s\t%s\t" % (inquiry.visitors, inquiry.speakers, inquiry.signers,)
    tsv      += "%s\n"         % (NEEDED[inquiry.letters],)
    if len(inquiry.countries.all()) > 1:
        for country in range(1,len(inquiry.countries.all())):
            tsv += "%s\n"      % (inquiry.countries.all()[country],)
    if inquiry.letters:
        tsv  += "\n\tLast Name\tFirst Name\tMiddle Name\tOccupation\tGender\t"
        tsv  += "DOB\tCitizenship\tBirth\tResidence\n"
        for visitor in visitors:
            tsv += "\t%s\t"   % (visitor.surname,)
            tsv += "%s\t"     % (visitor.givenname,)
            tsv += "%s\t"     % (visitor.middlename,)   
            tsv += "%s\t"     % (visitor.occupation,)
            tsv += "%s\t%s\t" % (visitor.gender, visitor.dob,)
            tsv += "%s\t"     % (visitor.citizenship,)
            tsv += "%s\t"     % (visitor.native,)
            tsv += "%s\n"     % (visitor.residence,)
    msg.attach("request.tsv", tsv, "text/tab-separated-values")
    msg.send()
    return render_to_response("visitors/thanks.html", locals())

##############################################################################

def bios(request,inquiry_id):
    countries = Country.objects.all()
    inquiry   = get_object_or_404(Inquiry, pk=int(inquiry_id))
    VisitorFormset = inlineformset_factory(Inquiry, Visitor,
                                           form=VisitorForm,
                                           extra=inquiry.visitors)

    if request.method == "POST":
        visitor_formset = VisitorFormset(request.POST, instance=inquiry)
        if visitor_formset.is_valid():
            visitor = visitor_formset.save()
            return HttpResponseRedirect("/resources/visitors/thanks/%s/" % (inquiry.id,))
        else:
            pass
    else:
        visitor_formset = VisitorFormset(instance=inquiry)
        visitor_forms   = Paginator(visitor_formset,1)
#       page = request.GET.get("page")
#       try:
#           visitor_form = visitor_forms.page(page)
#       except PageNotAnInteger:
#           visitor_form = visitor_forms.page(1)
#       except EmptyPage:
#           visitor_form = visitor_forms.page(visitor_forms.num_pages)
#       details = visitor_form.object_list[0]
#       prefix = details.prefix

    return render_to_response("visitors/visitors.html", locals(),
                              context_instance=RequestContext(request))

##############################################################################

def index(request):
    countries = Country.objects.all()

resources/templates/visitors/deliver.html
<!DOCTYPE html>
<html lang="en-US">
 <head>
  <meta charset="UTF-8" />
  <meta name="generator"
        content="Linux, Emacs and me" />
  <meta name="author"
        content="Kevin Cole" />
  <link rel="license"
        title="[Kevin Cole]"
        href="http://research.gallaudet.edu/~kjcole/license/notice.php" />
  <link rel="author"
        title="[Kevin Cole]"
        href="http://research.gallaudet.edu/~kjcole/" />
<title>Re: Visit Inquiry - 
       ({{inquiry.arr_date|date:"F j, Y"}} to 
        {{inquiry.dep_date|date:"F j, Y"}})</title>
<style type="text/css">
body     {font-family: Verdana, Arial, Helvetica, sans-serif;
          font-size:   16px;}
fieldset {margin:           10px;
          background-color: #dfffff;
          border:           thin solid #ff7f7f;}
legend   {background-color: #ffffc0;
          border:           thin solid #ff7f7f;
          color:            #ff3f3f;
          font-weight:      bold;}
.center  {margin:           1em auto;
          text-align:       center;}
table, tbody, tr, th, td { border: none; }
</style>
<head>
<body itemscope itemtype="http://schema.org/WebPage">
<article id="essence" role="main"
         style="margin:0px auto;">

<div style="border:1px solid black; width:715px; padding:20px;">
<div><img
 src="http://research.gallaudet.edu/images/logos/Gallaudet-750.png"
 alt="Gallaudet University" width="281" height="159"
 style="display:block; margin:auto; width:281px; height:150px" />
</div>

<section style="page-break-after:always;">
<p style="text-align:right;">{{today|date:"F j, Y"}}</p>
<p>Dear {{inquiry.requester}},</p>

<p>Your request for special support while visiting Gallaudet University
has been received. We will be in touch shortly. Please save this
receipt.</p>

<p>Please know that you may visit Gallaudet University without our
office's support. Also, you may contact faculty members or academic
units directly. For information about visiting Gallaudet, see:
<a href="http://www.gallaudet.edu/">http://www.gallaudet.edu/</a>. To
reach our Visitor Center (tour schedules, campus housing, etc.) see
<a href="http://www.gallaudet.edu/visitors_center.html">http://www.gallaudet.edu/visitors_center.html</a>.</p>

<p>If you are interested in studying at Gallaudet, see 
<a href="http://www.gallaudet.edu/welcome_international_visitors.html">http://www.gallaudet.edu/welcome_international_visitors.html</a>.</p>

<p>Now we will consider your request for special support, as in
arranging meetings or class visits. If our office can support your
visit, we can provide up to two (2) days of support only.</p>

<p>Send all correspondence to email &lt;<a
 href="mailto:intl.visit@gallaudet.edu">intl.visit@gallaudet.edu</a>&gt;.</p>

{% if inquiry.interpreter %}
  <p>IMPORTANT: From your answer on the form, it appears
  that <strong>you need sign language interpreters</strong> for easy
  communication while at Gallaudet. That is, interpreting from</p>

  <p style="text-align:center;">American Sign Language (ASL)
  &larr;&rarr; spoken English</p>

  <p style="text-align:center;">OR</p>

  <p style="text-align:center;">ASL &larr;&rarr; your spoken language
  or sign language.</p>

  <p>We can give two hours of ASL &larr;&rarr; English interpreting
  without cost to you.  After that, we can hire interpreters at your
  expense. We can not provide interpreters for other languages; you
  must bring them with you.</p>
{% endif %}

<p>Thank you for your interest in Gallaudet University.</p>

<p>--&nbsp;<br />
The Office of International Programs &amp; Services<br />
Dawes House, Gallaudet University<br />
800 Florida Avenue, N.E.<br />
Washington, D.C. 20002</p>

<p>Send all correspondence to email &lt;<a 
href="mailto:intl.visit@gallaudet.edu">intl.visit@gallaudet.edu</a>&gt;.</p>
</section>

<section style="page-break-after:always;">
<h1 style="text-align:center;">Receipt</h1>

<fieldset style="margin:35px 10px;background-color:#dfffff;border:thin solid #ff7f7f;">
<legend style="background-color:#ffffc0;border:thin solid #ff7f7f;color:#ff3f3f;font-weight:bold;">General Information</legend>

<table style="table-layout:fixed; width:640px;">
<tbody style="vertical-align:top;">

<tr><td style="width:30%;">Countries:</td>
<td style="width:70%;">
{% for country in inquiry.countries.all %}
{{country|safe}}
{% if not forloop.last %}<br />{% endif %}
{% endfor %}</td></tr>

<tr><td style="width:30%;">Arrival date:</td>
<td style="width:70%;">{{inquiry.arr_date}}</td></tr>

<tr><td style="width:30%;">Arrival time:</td>
<td style="width:70%;">{{inquiry.get_arr_time_display}}</td></tr>

<tr><td style="width:30%;">Departure date:</td>
<td style="width:70%;">{{inquiry.dep_date}}</td></tr>

<tr><td style="width:30%;">Departure time:</td>
<td style="width:70%;">{{inquiry.get_dep_time_display}}</td></tr>

<tr><td style="width:30%;">Requester:</td>
<td style="width:70%;">{{inquiry.requester}}</td></tr>

<tr><td style="width:30%;">Organization:</td>
<td style="width:70%;">{{inquiry.organization}}</td></tr>

<tr><td style="width:30%;">Email address:</td>
<td style="width:70%;">{{inquiry.email}}</td></tr>

<tr><td style="width:30%;">Phone number:</td>
<td style="width:70%;">{{inquiry.phone}}</td></tr>

<tr><td style="width:30%;">Number of visitors:</td>
<td style="width:70%;">{{inquiry.visitors}}</td></tr>

<tr><td style="width:30%;">Number&nbsp;of&nbsp;English&nbsp;speakers:</td>
<td style="width:70%;">{{inquiry.speakers}}</td></tr>

<tr><td style="width:30%;">Number&nbsp;of&nbsp;ASL&nbsp;users:</td>
<td style="width:70%;">{{inquiry.signers}}</td></tr>

<tr><td style="width:30%;">Purpose of visit:</td>
<td style="width:70%;">{{inquiry.purpose}}</td></tr>

<tr><td style="width:30%;">Need letters?:</td>
<td style="width:70%;">{{inquiry.get_letters_display}}</td></tr>

</tbody>
</table>
</fieldset>
</section>

{% if visitors %}
{% for visitor in visitors %}
<section style="page-break-after:always;">
<fieldset style="margin:35px 10px;background-color:#dfffff;border:thin solid #ff7f7f;">
  <legend  style="background-color:#ffffc0;border:thin solid #ff7f7f;color:#ff3f3f;font-weight:bold;">Visitor #{{forloop.counter}}</legend>
  <table style="table-layout:fixed; width:640px;">
  <colgroup>
    <col span="1" style="width:30%;" />
    <col span="1" style="width:70%;" />
  </colgroup>
  <tbody style="vertical-align:top;">
  <tr>
  <td style="30%">Family name(s):</td>
  <td style="70%">{{visitor.surname}}</td>
  </tr>
  <tr>
  <td style="30%">Given name(s):</td>
  <td style="70%">{{visitor.givenname}}</td>
  </tr>
  <tr>
  <td style="30%">Middle name(s):</td>
  <td style="70%">{{visitor.middlename}}</td>
  </tr>
  <tr>
  <td style="30%">Occupation:</td>
  <td style="70%">{{visitor.occupation}}</td>
  </tr>
  <tr>
  <td style="30%">Gender:</td>
  <td style="70%">{{visitor.gender}}</td>
  </tr>
  <tr>
  <td style="30%">Date of birth:</td>
  <td style="70%">{{visitor.dob}}</td>
  </tr>
  <tr>
  <td style="30%">Country of citizenship:</td>
  <td style="70%">{{visitor.citizenship|safe}}</td>
  </tr>
  <tr>
  <td style="30%">Country of birth:</td>
  <td style="70%">{{visitor.native|safe}}</td>
  </tr>
  <tr>
  <td style="30%">Country of legal residence:</td>
  <td style="70%">{{visitor.residence|safe}}</td>
  </tr>
  </tbody>
  </table>
</fieldset>
</section>
{% endfor %}
{% endif %}

<section style="page-break-after:always;">
<p
 style="font-size:10pt; font-weight:bold; color:#00447C; text-align:center; vertical-align:top; padding-top:6px;">
Dawes House &bull; 
800 Florida Avenue, NE &bull; 
Washington, DC 20002-3695<br />
202-651-5575 &bull; 
intl.visit@gallaudet.edu &bull; 
www.gallaudet.edu
</p>
</section>

</div>
</article>
</body>
</html>

resources/templates/visitors/testicle.html
{% extends "visitors.html" %}
{% block title %}INTERNATIONAL VISITOR REQUEST FORM{% endblock %}

{% block styles %}
<style type="text/css">
body     {font-family: Verdana, Arial, Helvetica, sans-serif;
          font-size:   16px;}

fieldset {margin:           10px;
          background-color: #dfffff;              /* sort of cyan */
          border:           thin solid #ff7f7f;}  /* pink         */

legend   {background-color: #ffffc0;              /* light yellow */
          border:           thin solid #ff7f7f;   /* pink         */
          color:            #ff3f3f;              /* light red    */
          font-weight:      bold;}

input,
select, option,
textarea {border:      1px solid black;
          font-family: fixed;
          font-size:   16px;
          vertical-align: top;}

.center  {margin:           1em auto;
          text-align:       center;}

table, tbody, tr, th, td { border: none; }
</style>
{% endblock %}

{% block scripts %}
  <!-- jQuery UI Autocomplete script stuff -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"
          type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
          type="text/javascript"></script>
  <script src="https://jquery-ui.googlecode.com/svn/tags/latest/external/jquery.bgiframe-2.1.2.js"
          type="text/javascript"></script>
  <script src="https://jquery-ui.googlecode.com/svn/tags/latest/ui/minified/i18n/jquery-ui-i18n.min.js"
          type="text/javascript"></script>
  <script src="/scripts/ragulib.js"
          type="text/javascript"></script>

<script type="text/javascript">
function OnSubmitForm() {
  var form = document.getElementById("general");
  if      (form.letters[0].checked == true) form.action = "letters.php";
  else if (form.letters[1].checked == true) form.action = "deliver.php";
  return true;
}
</script>
{% endblock %}

{% block content %}
<main role="main">
<article id="essence" role="main">
<h1 class="center">INTERNATIONAL VISITOR REQUEST FORM</h1>

<p>Please provide <strong>ALL</strong> the requested information.</p>

<form id="general" name="general" action="." method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

</article>
</main>
{% endblock %}