resources/books/urls.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2008.11.30
#

from django.conf.urls.defaults import *

from resources.books.views import search, contact, add_publisher

urlpatterns = patterns('',
    (r'^search/$', search),
    (r'^contact/$', contact),
    (r'^addpub/$', add_publisher),
)

resources/urls.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2012.03.12
#
# For help with all the now undocumented updates, see:
#    http://code.djangoproject.com/wiki/NewFormsAdminBranch
#
# For help with the images and css, see:
#    http://www.djangoproject.com/documentation/static_files/
#
# See also?
#    http://code.djangoproject.com/wiki/IrcFAQ#MediaURL
#    http://www.djangoproject.com/documentation/templates_python/#subclassing-context-requestcontext
#    http://www.djangoproject.com/documentation/settings/#media-root
#    http://www.djangoproject.com/documentation/settings/#media-url
#
# 2008.11.30 KJC - DEPLOY! Added "django/" to all patterns (See p. 279)
# 2008.12.01 KJC - Oops. Changed "^django/" to "^". See updated info at:
#                  http://docs.djangoproject.com/en/dev/howto/deployment/modpython/
# 2008.12.01 KJC - Split into multiple urls.py files
# 2009.09.18 KJC - Changed ^admin/ to upcoming Django 1.3 format
# 2012.02.22 KJC - Refactored / merged from /psite/ into this "instance"
# 2012.03.11 KJC - Adding in Research at Gallaudet (rag)
# 2012.03.12 KJC - Changing it to Research at Gallaudet University (ragu)
# 2012.05.02 KJC - Adding in Preliminary Screening Survey (screening)
# 2013.11.10 KJC - Adding an International Visitors form...

from django.conf.urls.defaults import patterns, include, url
from django.contrib            import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #   url(r'^$',          'resources.views.home', name='home'),
    #   url(r'^resources/', include('resources.foo.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/',     include(admin.site.urls)),

    url(r'^books/',     include('resources.books.urls')),
    url(r'^mhd/',       include('resources.mhd.urls')),
    url(r'^ragu/',      include('resources.ragu.urls')),
    url(r'^screening/', include('resources.screening.urls')),
    url(r'visitors/',   include('resources.visitors.urls')),

    # Probably now a better way to handle the following two lines...
    #url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/kjcole/Django/images'}),
    #url(r'^css/(?P<path>.*)$',    'django.views.static.serve', {'document_root': '/home/kjcole/Django/css'}),
)

resources/books/models.py
from django.db import models

class Publisher(models.Model):
    name           = models.CharField(max_length=30)
    address        = models.CharField(max_length=50)
    city           = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country        = models.CharField(max_length=50)
    website        = models.URLField()
    
    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    first_name = models.CharField(max_length=30)
    last_name  = models.CharField(max_length=40)
    email      = models.EmailField()
    headshot   = models.ImageField(upload_to="/tmp")
    
    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        ordering = ["last_name", "first_name"]

class Book(models.Model):
    title            = models.CharField(max_length=100)
    authors          = models.ManyToManyField(Author)
    publisher        = models.ForeignKey(Publisher)
    publication_date = models.DateTimeField()
    num_pages        = models.PositiveSmallIntegerField(blank=True, null=True)
    
    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["title"]

resources/books/forms.py
from models import Publisher
from django import forms

TOPIC_CHOICES = (("general", "General enquiry"),
                 ("bug", "Bug report"),
                 ("suggestion", "Suggestion"),)

class ContactForm(forms.Form):
    topic = forms.ChoiceField(choices=TOPIC_CHOICES)
    message = forms.CharField(widget=forms.Textarea())
    sender = forms.EmailField(required=False)
    
    def clean_message(self):
        message = self.cleaned_data.get("message", "")
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message
    
class PublisherForm(forms.ModelForm):
    
    class Meta:
        model = Publisher

resources/books/views.py
# Books views from Chapter 7

from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.mail import send_mail
from resources.books.models import Book
from resources.books.forms import ContactForm, PublisherForm

def search(request):
    query = request.GET.get("q", "")
    if query:
        qset = (
            Q(title__icontains=query) |
            Q(authors__first_name__icontains=query) |
            Q(authors__last_name__icontains=query)
        )
        results = Book.objects.filter(qset).distinct()
    else:
        results = []
    return render_to_response("books/search.html", 
                              {"results": results,
                               "query":   query})

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            topic = form.cleaned_data["topic"]
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["sender"]
            send_mail("Feedback from your site, topic: %s" % (topic,),
                      message, sender, ["kjcole@gri.gallaudet.edu"])
            return HttpResponseRedirect("/books/contact/thanks/")
    else:
        form = ContactForm()
    return render_to_response("books/contact.html", {"form": form})

def add_publisher(request):
    if request.method == "POST":
        form = PublisherForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/books/add_publisher/thanks")
    else:
        form = PublisherForm()
    return render_to_response("books/add_publisher.html", {"form": form})

resources/templates/books/add_publisher.html
{% extends "skeleton.html" %}
{% block title %}Add publisher{% endblock %}
{% block style %}
<style type="text/css">
  ul.errorlist {margin: 0; padding: 0;}
  .errorlist li {background-color: #ff0000;
                 color:            #ffffff;
                 display:          block;
                 font-size:        10px;
                 margin:           0 0 3px;
                 padding:          4px 5px;}
</style>
{% endblock %}

{% block content%}
<h1>Add publisher</h1>
<form action="." method="POST">
  <table>
    {{form.as_table}}
  </table>
  <p><input type="submit" value="Submit" /></p>
</form>
{% endblock %}

resources/templates/books/contact.html
{% extends "skeleton.html" %}
{% block title %}Contact us{% endblock %}
{% block style %}
<style type="text/css">
  ul.errorlist {margin: 0; padding: 0;}
  .errorlist li {background-color: #ff0000;
                 color:            #ffffff;
                 display:          block;
                 font-size:        10px;
                 margin:           0 0 3px;
                 padding:          4px 5px;}
</style>
{% endblock %}

{% block content%}
<h1>Contact us</h1>
<form action="." method="POST">
  <div class="fieldWrapper">
    {{form.topic.errors}}
    <label for="id_topic">Type of feedback:</label>
    {{form.topic}}
  </div>
  <div class="fieldWrapper">
    {{form.message.errors}}
    <label for="id_message">Message body:</label>
    {{form.message}}
  </div>
  <div class="fieldWrapper">
    {{form.sender.errors}}
    <label for="id_sender">Your e-mail address:</label>
    {{form.sender}}
  </div>
  <p><input type="submit" value="Submit" /></p>
</form>
{% endblock %}

resources/templates/books/search.html
{% extends "skeleton.html" %}
{% block title %}Search {% if query %}Results{% endif %}{% endblock %}

{% block content%}
  <form action="." method="GET">
    <label for="q">Search:</label>
    <input type="text" name="q" value="{{query|escape}}" />
    <input type="submit" value="Search" />
  </form>

  {% if query %}
    <h2>Results for "{{query|escape}}":</h2>
    {% if results %}
      <ul>
      {% for book in results %}
        <li>{{book}}</li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No books found</p>
    {% endif %}
  {% endif %}
{% endblock %}