resources/screening/urls.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2013.07.16
#
# 2013.07.16 KJC - Switching to class-based generic views from function-based
#

from django.conf.urls.defaults import *
from resources.screening.views import *
from django.views.generic.base import TemplateView

urlpatterns = patterns("",
#   (r"^.*$",       TemplateView.as_view(template_name="screening/closed.html")),
    (r"^$",         TemplateView.as_view(template_name="screening/index.html")),
#   (r"^credits/$", TemplateView.as_view(template_name="screening/credits.html")),
#   (r"^consent/$", TemplateView.as_view(template_name="screening/consent.html")),
#   (r"^stop/$",    TemplateView.as_view(template_name="screening/stop.html")),
    (r"^sesame/$",   "django.contrib.auth.views.login", 
                                        {"template_name": "screening/sesame.html"}),
#   (r"^begin/$",                    winnow),
#   (r"^winnow_confirm/$",           winnow_confirm),
#   (r"^public_confirm/(\d{1,7})/$", public_confirm),
#   (r"^private_confirm/(\w{8})/$",  private_confirm),
#   (r"^public_collect/(\d{1,7})/$", public_collect),
#   (r"^private_collect/$",          private_collect),
#   (r"^public_students/$",          public_students),
#   (r"^public_counts/$",            public_counts),
#   (r"^public_sources/$",           public_sources),
#   (r"^public_contact/$",           public_contact),
#   (r"^private_contact/$",          private_contact),
#   (r"^public_participation/$",     public_participation),
#   (r"^private_participation/$",    private_participation),
    (r"^track/$",                    track),
    (r"^track_agency/(\d{1,7})/$",   track_agency),
    (r"^track_private/(\w{8})/$",    track_private),
)

resources/urls.py
# Last modified by Kevin Cole <kjcole@gri.gallaudet.edu> 2012.03.12
#
# For help with all the now undocumented updates, see:
#    http://code.djangoproject.com/wiki/NewFormsAdminBranch
#
# For help with the images and css, see:
#    http://www.djangoproject.com/documentation/static_files/
#
# See also?
#    http://code.djangoproject.com/wiki/IrcFAQ#MediaURL
#    http://www.djangoproject.com/documentation/templates_python/#subclassing-context-requestcontext
#    http://www.djangoproject.com/documentation/settings/#media-root
#    http://www.djangoproject.com/documentation/settings/#media-url
#
# 2008.11.30 KJC - DEPLOY! Added "django/" to all patterns (See p. 279)
# 2008.12.01 KJC - Oops. Changed "^django/" to "^". See updated info at:
#                  http://docs.djangoproject.com/en/dev/howto/deployment/modpython/
# 2008.12.01 KJC - Split into multiple urls.py files
# 2009.09.18 KJC - Changed ^admin/ to upcoming Django 1.3 format
# 2012.02.22 KJC - Refactored / merged from /psite/ into this "instance"
# 2012.03.11 KJC - Adding in Research at Gallaudet (rag)
# 2012.03.12 KJC - Changing it to Research at Gallaudet University (ragu)
# 2012.05.02 KJC - Adding in Preliminary Screening Survey (screening)
# 2013.11.10 KJC - Adding an International Visitors form...

from django.conf.urls.defaults import patterns, include, url
from django.contrib            import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #   url(r'^$',          'resources.views.home', name='home'),
    #   url(r'^resources/', include('resources.foo.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/',     include(admin.site.urls)),

    url(r'^books/',     include('resources.books.urls')),
    url(r'^mhd/',       include('resources.mhd.urls')),
    url(r'^ragu/',      include('resources.ragu.urls')),
    url(r'^screening/', include('resources.screening.urls')),
    url(r'visitors/',   include('resources.visitors.urls')),

    # Probably now a better way to handle the following two lines...
    #url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/kjcole/Django/images'}),
    #url(r'^css/(?P<path>.*)$',    'django.views.static.serve', {'document_root': '/home/kjcole/Django/css'}),
)

resources/screening/models.py
# Models for the Preliminary Screening Survey for the Supplemental
# Survey of the Annual Survey. What a mouthful.
#
# Last modified by Kevin Cole <kjcole@gallaudet.edu>
#

from django.db import models

PARTICIPATION = ((2,"Yes, please do so."),
                 (1,"Yes, but someone else must approve participation."),
                 (0,"No, I respectfully decline."))

class State (models.Model):
    usps = models.CharField(max_length=2, editable=False)
    name = models.CharField(max_length=50, editable=False)

    def __unicode__(self):
        return "%2s (%s)" % (self.usps, self.name)

    class Meta:
        ordering = ["usps"]

class Agency (models.Model):
    id               = models.IntegerField(primary_key=True, editable=False)
    password         = models.CharField(max_length=8, editable=False)
    changed          = models.DateTimeField("last changed", auto_now=True, editable=False)
    in_annual_survey = models.BooleanField("in Annual Survey?", editable=False)
    in_sample        = models.BooleanField("in sample?", editable=False)
    as_contact       = models.BooleanField("contacted re AS?", editable=False)
    frequency        = models.PositiveSmallIntegerField(editable=False)
    agency_name      = models.CharField(max_length=60, editable=False)
    street           = models.CharField(max_length=30, editable=False)
    city             = models.CharField(max_length=22, editable=False)
    county           = models.CharField(max_length=30, editable=False)
    state            = models.CharField(max_length=2, editable=False)
    zip              = models.PositiveIntegerField(editable=False)
    zip4             = models.PositiveSmallIntegerField(null=True, editable=False)
    phone            = models.CharField(max_length=14, editable=False)
    enrollment       = models.IntegerField(editable=False)
    agency_type      = models.PositiveSmallIntegerField(editable=False)
    lowest           = models.CharField(max_length=2, editable=False)
    highest          = models.CharField(max_length=2, editable=False)
    school_count     = models.PositiveIntegerField(editable=False)
    students_deaf    = models.PositiveSmallIntegerField(null=True)
    is_source_iep    = models.NullBooleanField("Individual Education Program (IEP)")
    is_source_ifsp   = models.NullBooleanField("Individual Family Service Plan (IFSP)")
    is_source_504    = models.NullBooleanField("Section 504 Plan")
    is_source_ada    = models.NullBooleanField("Americans with Disabilities Act (ADA) Title II Plan")
    is_source_other  = models.NullBooleanField("other source of identification")
    contact_name     = models.CharField(max_length=255,  null=True)
    contact_title    = models.CharField(max_length=255,  null=True)
    contact_email    = models.EmailField(max_length=255, null=True)
    contact_phone    = models.CharField(max_length=255,  null=True)
    participation    = models.PositiveSmallIntegerField(null=True,
                                                        choices=PARTICIPATION)
    visited          = models.BooleanField("Form visited?", editable=False)

    def __unicode__(self):
        return self.agency_name

    class Meta:
        ordering = ["state", "agency_name"]
        get_latest_by = "changed"
        verbose_name_plural = "agencies"

class Private_School (models.Model):
    id                = models.CharField(max_length=8, primary_key=True, editable=False)
    password          = models.CharField(max_length=8, editable=False)
    changed           = models.DateTimeField("last changed", auto_now=True, editable=False)
    in_annual_survey  = models.BooleanField("in Annual Survey?", editable=False)
    in_sample         = models.BooleanField("in sample?", editable=False)
    as_contact        = models.BooleanField("contacted re AS?", editable=False)
    frequency         = models.PositiveSmallIntegerField(editable=False)
    school_name       = models.CharField(max_length=50, editable=False)
    street            = models.CharField(max_length=40, null=True, editable=False)
    city              = models.CharField(max_length=22, editable=False)
    fips_county_code  = models.PositiveSmallIntegerField(editable=False)
    county            = models.CharField(max_length=20, editable=False)
    fips_state_code   = models.PositiveSmallIntegerField(editable=False)
    state             = models.CharField(max_length=2, editable=False)
    zip               = models.PositiveIntegerField(editable=False)
    zip4              = models.PositiveSmallIntegerField(null=True, editable=False)
    phone             = models.CharField(max_length=10, null=True, editable=False)
    students_total    = models.PositiveSmallIntegerField(null=True, editable=False)
    students_pk       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_k        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_01       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_02       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_03       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_04       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_05       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_06       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_07       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_08       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_09       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_10       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_11       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_12       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_ug       = models.PositiveSmallIntegerField(null=True, editable=False)
    students_native   = models.PositiveSmallIntegerField(null=True, editable=False)
    students_asian    = models.PositiveSmallIntegerField(null=True, editable=False)
    students_latino   = models.PositiveSmallIntegerField(null=True, editable=False)
    students_black    = models.PositiveSmallIntegerField(null=True, editable=False)
    students_white    = models.PositiveSmallIntegerField(null=True, editable=False)
    students_pacific  = models.PositiveSmallIntegerField(null=True, editable=False)
    students_multi    = models.PositiveSmallIntegerField(null=True, editable=False)
    students_deaf     = models.PositiveSmallIntegerField(null=True)
    is_source_iep     = models.NullBooleanField("Individual Education Program (IEP)")
    is_source_ifsp    = models.NullBooleanField("Individual Family Service Plan (IFSP)")
    is_source_504     = models.NullBooleanField("Section 504 Plan")
    is_source_ada     = models.NullBooleanField("Americans with Disabilities Act (ADA) Title II Plan")
    is_source_other   = models.NullBooleanField("other source of identification")
    contact_name      = models.CharField(max_length=255,  null=True)
    contact_title     = models.CharField(max_length=255,  null=True)
    contact_email     = models.EmailField(max_length=255, null=True)
    contact_phone     = models.CharField(max_length=255,  null=True)
    participation     = models.PositiveSmallIntegerField(null=True,
                                                         choices=PARTICIPATION)
    visited           = models.BooleanField("Form visited?", editable=False)

    def __unicode__(self):
        return self.school_name

    class Meta:
        ordering = ["state", "school_name"]
        get_latest_by = "changed"

class Public_School (models.Model):
    id                 = models.BigIntegerField(primary_key=True, editable=False)
    changed            = models.DateTimeField("last changed", auto_now=True, editable=False)
    in_annual_survey   = models.BooleanField("in Annual Survey?", editable=False)
    agency             = models.ForeignKey(Agency, editable=False)
    agency_name        = models.CharField(max_length=60, editable=False)
    school_id          = models.PositiveIntegerField(editable=False)
    school_name        = models.CharField(max_length=50, editable=False)
    street             = models.CharField(max_length=30, editable=False)
    city               = models.CharField(max_length=25, editable=False)
    county_code        = models.PositiveIntegerField(null=True, editable=False)
    county             = models.CharField(max_length=33, null=True, editable=False)
    state              = models.CharField(max_length=2, editable=False)
    zip                = models.PositiveIntegerField(editable=False)
    zip4               = models.PositiveSmallIntegerField(null=True, editable=False)
    phone              = models.CharField(max_length=10, null=True, editable=False)
    students_total     = models.PositiveSmallIntegerField(null=True, editable=False)
    students_pk        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_k         = models.PositiveSmallIntegerField(null=True, editable=False)
    students_01        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_02        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_03        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_04        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_05        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_06        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_07        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_08        = models.PositiveSmallIntegerField(null=True, editable=False)
    students_09        = models.PositiveSmallIntegerField(null=True, editable=False)

resources/templates/screening/consent.html
{% extends "screening.html" %}

{% block styles %}
<style type="text/css">
fieldset {background-color: #f0ffff;
          border:           thin solid #8b4513;
          margin:           1.2em auto;}

.flow    {background-color: #ffffff;
          border:           none;
          margin:           1.2em auto;}

legend   {font-weight:      bold;
          background-color: #f0ffff;
          color:            #8b4513;
          border:           thin solid #8b4513;}

input    {font-family:      fixed;
          background-color: #ffffd0;
          text-align:       right;
          border:           thin solid #8b4513;}
</style>
{% endblock %}

{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">

<p>Welcome!  This survey is being conducted by the Gallaudet Research
Institute (GRI) to estimate the size of the population of all deaf and
hard of hearing children and youth served by public and private
schools throughout the United States and to determine their
distribution among states and the schooling sectors within each
state.</p>

<p>Your responses are strictly confidential. Records are kept on a
secure and password protected server to which only authorized GRI
investigators have access. No participants will be identified in any
report or publication. If any federal or state agencies exercise their
authority to access our records, the GRI will act within the law to
protect your privacy.</p>

<p>While your responses to this survey are very important to us,
participation is completely voluntary. You may stop participating at
any time.</p>

<p>By completing the survey you are agreeing to participate.</p>

<p>If you have questions or concerns, please contact the Annual Survey
Coordinator, Kay Lam, by e-mail
at <a href="mailto:kay.lam@gallaudet.edu">kay.lam@gallaudet.edu</a>,
or Rue Winiarczyk
at <a
href="mailto:rowena.winiarczyk@gallaudet.edu">rowena.winiarczyk@gallaudet.edu</a>;
both Ms. Lam and Ms. Winiarczyk, as well as the GRI Associate
Director, Charles Reilly, may be contacted by telephone at (202)
651-5575 [v/tty].</p>

<p><strong>Consent Statement:</strong></p>

<ul>

<li>Click the '<strong>Yes, continue</strong>' button (below), to
confirm your willingness to participate in the survey.</li>

<li>Or, click the '<strong>No, stop here</strong>' button (below), to
verify that you are unable to participate in the survey<br />
at this time.</li>
</ul>

<p><strong>Do you consent to participate in this survey?</strong></br />
(Note: Before clicking the Next button, you may print a copy of this
page for your records.)</p>

<form action="." method="get">
<fieldset class="flow">
<div style="width:100%;">
<div style="width:50%; float:left; text-align:center;"><button type="button"
onclick="window.location.replace('/resources/screening/stop/')">No,
stop here</button></div>
<div style="width:50%; float:left; text-align:center;"><button type="button"
  onclick="window.location.replace('/resources/screening/begin/')">Yes, 
continue</button></div>
</div>
</fieldset>
</form>

</article>
</main>
{% endblock %}

resources/templates/screening/forbidden.html
{% extends "screening.html" %}

{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">

<h1>Forbidden</h1>
<p>Get out! Or I'm calling the cops!</p>

</article>
</main>
{% endblock %}

resources/templates/screening/maintenance.html
{% extends "screening.html" %}

{% block content %}
<main role="main">
<article id="essence" style="background-color:#a7a7a7; margin:0px auto;" role="main">

<p class="center"><span style="font-size:140%; font-weight:bold;">Supplemental Survey Project of the<br />
Annual Survey of Deaf and Hard of Hearing Children 
and Youth</span></p>

<p class="center">Annual Survey Coordinator<br />
<a style="background-color:#a0a0a0;"
href="http://www.gallaudet.edu/Faculty-Staff/Gallaudet_Research_Institute/Lam_Kay.html">Kay
Lam</a><br /> 
<a style="background-color:#a0a0a0;" href="http://research.gallaudet.edu/">Gallaudet Research Institute</a>
&bull; <a 
style="background-color:#a0a0a0;" href="http://www.gallaudet.edu/">Gallaudet University</a><br />
and<br />
Supplemental Survey Project Director<br />
<a style="background-color:#a0a0a0;"
href="http://www.redlands.edu/academics/school-of-education/4320.aspx">Ross
E. Mitchell, Ph.D.</a><br />
<a style="background-color:#a0a0a0;" href="http://www.redlands.edu/academics/school-of-education.aspx">School
of Education</a> &bull; <a style="background-color:#a0a0a0;" href="http://www.redlands.edu/">University of
Redlands</a></p>

<hr />

<div style="margin-left: 20%; margin-right: 20%;">
<ul>
<li><a style="background-color:#a0a0a0;" href="/resources/screening/consent/"><strong>Begin the survey</strong></a></li>
<li><a style="background-color:#a0a0a0;" href="/resources/screening/credits/">Credits</a></li>
</ul>
</div>

<div style="font-family:Courier; border:2px #ff0000 solid; border-radius:25px; box-shadow: 10px 10px 5px #666666; position:relative; top:-200px; width:750px; z-index:1; background-color:#ffffaf;">
<h1 style="text-align:center; color:#ff0000;">System going down for scheduled maintenance</h1>
<h2 style="text-align:center; color:#ff0000;">This system will be unavailable
from
<br /><strong>June 7, 2012 8:00 PM (EDT)</strong> until 
<strong>June 8, 2012 6:00 AM (EDT)</strong></h2>
</div>

</article>
</main>
{% endblock %}

resources/templates/screening/private_confirm.html
{% extends "screening.html" %}

{% block styles %}
<style type="text/css">
fieldset {background-color: #f0ffff;
          border:           thin solid #8b4513;
          margin:           1.2em auto;}

.flow    {background-color: #ffffff;
          border:           none;
          margin:           1.2em auto;}

legend   {font-weight:      bold;
          background-color: #f0ffff;
          color:            #8b4513;
          border:           thin solid #8b4513;}

input    {font-family:      fixed;
          background-color: #ffffd0;
          text-align:       right;
          border:           thin solid #8b4513;}
</style>
{% endblock %}

{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">

  <h1>{{school.school_name|safe}}</h1>

  <form action="/resources/screening/private_collect/"
        method="get">
    {% csrf_token %}

    <fieldset>

    <p>You have selected</p>
    <h2 class="center">{{school.school_name|safe}}</h2>.

    <p>If this is correct, please click the <strong>Next
    &rarr;</strong> button below. Otherwise, click the <strong>&larr;
    Back</strong> button.</p>

    <div style="width:100%">
      <div style="width:50%; float:left; text-align:center;">
        <button type="button" onclick="window.history.back()">&larr; Back</button>
      </div>
      <div style="width:50%; float:left; text-align:center;">
        <button type="submit">Next &rarr;</button>
      </div>
    </div>

    </fieldset>

  </form>

</article>
</main>
{% endblock %}

resources/templates/screening/private_contact.html
{% extends "screening.html" %}

{% block styles %}
<style type="text/css">
table, tbody, tr, td {font-size:100%; border: none;}

.error   {color:            #af0000;
          font-weight:      bold;}

fieldset {background-color: #f0ffff;
          border:           thin solid #8b4513;
          margin:           1.2em auto;}

.flow    {background-color: #ffffff;
          border:           none;
          margin:           1.2em auto;}

legend   {font-weight:      bold;
          background-color: #f0ffff;
          color:            #8b4513;
          border:           thin solid #8b4513;}

input    {font-family:      fixed;
          background-color: #ffffd0;
          border:           thin solid #8b4513;}
</style>
{% endblock %}


{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">

  <h1>{{school.school_name|safe}}</h1>

  <p>In the event that we should need to verify, correct or recover
  the data that you have submitted, please provide your contact
  information below.</p>

  <p>Don't forget to click <strong>Next &rarr;</strong> at the bottom
  of this page, when you have finished.</p>

  <form action="/resources/screening/private_contact/" method="post">
    {% csrf_token %}
    {{form.non_field_errors}}

    <fieldset>
      <legend>Contact Information</legend>

      <table style="width:100%;">
        <tbody style="vertical-align:top;">
        <tr>
          <td style="text-align:right;"><label 
              for="id_contact_name">Your full name:</label></td>
          <td>{{form.contact_name}}
              {% if form.contact_name.errors %}
                {% for error in form.contact_name.errors %}
                  <br /><span class="error">&bull; {{error}}</span>
                {% endfor %}
              {% endif %}</td>
        </tr>
        <tr>
          <td style="text-align:right;"><label
              for="id_contact_title">Your job title:</label></td>
          <td>{{form.contact_title}}
              {% if form.contact_title.errors %}
                {% for error in form.contact_title.errors %}
                  <br /><span class="error">&bull; {{error}}</span>
                {% endfor %}
              {% endif %}</td>
        </tr>
        <tr>
          <td style="text-align:right;"><label
              for="id_contact_email">Your e-mail address:</label></td>
          <td>{{form.contact_email}}
              {% if form.contact_email.errors %}
                {% for error in form.contact_email.errors %}
                  <br /><span class="error">&bull; {{error}}</span>
                {% endfor %}
              {% endif %}</td>
        </tr>
        <tr>
          <td style="text-align:right;"><label
              for="id_contact_phone">Your telephone number:<br />
                                     [999-999-9999]</label></td>
          <td>{{form.contact_phone}}
              {% if form.contact_phone.errors %}
                {% for error in form.contact_phone.errors %}
                  <br /><span class="error">&bull; {{error}}</span>
                {% endfor %}
              {% endif %}</td>
        </tr>
        </tbody>
      </table>
    </fieldset>

    <fieldset class="flow">
    <div style="width:100%">
      <div style="width:50%; float:left; text-align:center;">
        <button type="button" onclick="window.history.back()">&larr; Back</button>
      </div>
      <div style="width:50%; float:left; text-align:center;">
        <button type="submit">Next &rarr;</button>
      </div>
    </div>
    </fieldset>

  </form>

</article>
</main>
{% endblock %}

resources/templates/screening/private_selector.html
{% extends "screening.html" %}

{% block styles %}
<style type="text/css">
fieldset {background-color: #f0ffff;
          border:           thin solid #8b4513;
          margin:           1.2em auto;}

.flow    {background-color: #ffffff;
          border:           none;
          margin:           1.2em auto;}

legend   {font-weight:      bold;
          background-color: #f0ffff;
          color:            #8b4513;
          border:           thin solid #8b4513;}

input    {font-family:      fixed;
          background-color: #ffffd0;
          border:           thin solid #8b4513;}
</style>
{% endblock %}

{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">
  <h3 class="center">Private Schools for {{states.name|safe}}</h3>
  {% if privates %}
    <p>Select your private school from the list below:</p>
    <ul>
    {% for private in privates %}
      <li><a href="/resources/screening/private_confirm/{{private.id|safe}}">{{private.school_name|safe}}</a></li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No private schools found!</p>
  {% endif %}
</article>
</main>
{% endblock %}

resources/templates/screening/public_sources.html
{% extends "screening.html" %}

{% block styles %}
<style type="text/css">
fieldset {background-color: #f0ffff;
          border:           thin solid #8b4513;
          margin:           1.2em auto;}

.flow    {background-color: #ffffff;
          border:           none;
          margin:           1.2em auto;}

legend   {font-weight:      bold;
          background-color: #f0ffff;
          color:            #8b4513;
          border:           thin solid #8b4513;}
input    {font-family:      fixed;
          background-color: #ffffd0;
          text-align:       right;
          border:           thin solid #8b4513;}
</style>
{% endblock %}

{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">

  <h1>{{agency.agency_name|safe}}</h1>

  <p>Please fill out the following. Don't forget to click <strong>Next
  &rarr;</strong> at the bottom of this page, when you have
  finished.</p>

  <form action="/resources/screening/public_sources/" method="post">
    {% csrf_token %}
    {{form.non_field_errors}}

    <fieldset>
      <legend>Sources of identification</legend>

      <p>How were students in the schools on the previous screen identified
      as deaf or hard of hearing?  (Check all that apply.)</p>

      <p>
      {{form.is_source_iep}}
      <label for="id_is_source_iep">Individual Education Program (IEP)</label>
      {% if form.is_source_iep.errors %}
         {% for error in form.is_source_iep.errors %}
         <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <span class="error">&bull; {{error}}</span>
         {% endfor %}
      {% endif %}<br />

      {{form.is_source_ifsp}}
      <label for="id_is_source_ifsp">Individualized Family Service Plan (IFSP)</label>
      {% if form.is_source_ifsp.errors %}
         {% for error in form.is_source_ifsp.errors %}
         <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <span class="error">&bull; {{error}}</span>
         {% endfor %}
      {% endif %}<br />

      {{form.is_source_504}}
      <label for="id_is_source_504">Section 504 Plan</label>
      {% if form.is_source_504.errors %}
         {% for error in form.is_source_504.errors %}
         <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <span class="error">&bull; {{error}}</span>
         {% endfor %}
      {% endif %}<br />

      {{form.is_source_ada}}
      <label for="id_is_source_ada">Americans with Disabilities Act (ADA) Title II Plan</label>
      {% if form.is_source_ada.errors %}
         {% for error in form.is_source_ada.errors %}
         <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <span class="error">&bull; {{error}}</span>
         {% endfor %}
      {% endif %}<br />

      {{form.is_source_other}}
      <label for="id_is_source_other">Other</label>
      {% if form.is_source_other.errors %}
         {% for error in form.is_source_other.errors %}
         <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <span class="error">&bull; {{error}}</span>
         {% endfor %}
      {% endif %}
      </p>

    </fieldset>

    <fieldset class="flow">
    <div style="width:100%">
      <div style="width:50%; float:left; text-align:center;">
        <button type="button" onclick="window.history.back()">&larr; Back</button>
      </div>
      <div style="width:50%; float:left; text-align:center;">
        <button type="submit">Next &rarr;</button>
      </div>
    </div>
    </fieldset>

  </form>

</article>
</main>
{% endblock %}

resources/templates/screening/wip.html
{% extends "screening.html" %}

{% block content %}
<main role="main">
<article id="essence" style="margin:0px auto;" role="main">

<p>(Work In Progress...)</p>

</article>
</main>
{% endblock %}